apiVersion: dbaas.percona.com/v1alpha1
kind: DBclaim
metadata:
  name: psm-db-1
spec:
  compositionSelector:
    matchLabels:
      engine: psmdb
      storage: default
      network: default
  clusterSize: 1
  engineVersion: ""
  engineConfig: ""
---
apiVersion: dbaas.percona.com/v1alpha1
kind: DBclaim
metadata:
  name: pxc-db-1
spec:
  compositionSelector:
    matchLabels:
      engine: pxc
      storage: default
      network: default
  clusterSize: 1
  engineVersion: ""
  engineConfig: ""
