apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpxcdbtemplates.pxc.dbaas.percona.com
  labels:
    crossplane.io/xrd: xpxcdbtemplates.pxc.dbaas.percona.com
    engine: pxc

spec:

  writeConnectionSecretsToNamespace: crossplane-system

  compositeTypeRef:
    apiVersion: pxc.dbaas.percona.com/v1alpha1
    kind: XPXCDBtemplate

  resources:
  - name: configmap
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: template-config
              namespace: default
            data:
              name: data
        providerConfigRef:
          name: kubernetes-provider
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.data.name
    readinessChecks:
    - type: None