apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: dbtemplate-dbaas
  labels:
    crossplane.io/xrd: xdbtemplates.dbaas.percona.com
    engine: psmdb

spec:

  writeConnectionSecretsToNamespace: crossplane-system

  compositeTypeRef:
    apiVersion: dbaas.percona.com/v1alpha1
    kind: XDBtemplate

  resources:
  - name: PSMDBTemplate
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: psmdb.dbaas.percona.com/v1alpha1
            kind: PSMDBtemplate
            metadata:
              name: psmdb-default-template
              namespace: default
            spec:
              crVersion: 1.13.0
              image: percona/percona-server-mongodb:5.0.11-10
              allowUnsafeConfigurations: true
              upgradeOptions:
                apply: disabled
                schedule: "0 2 * * *"
              secrets:
                users: minimal-cluster
              replsets:

              - name: rs0
                size: 1
                volumeSpec:
                  persistentVolumeClaim:
                    resources:
                      requests:
                        storage: 3Gi

              sharding:
                enabled: true

                configsvrReplSet:
                  size: 1
                  volumeSpec:
                    persistentVolumeClaim:
                      resources:
                        requests:
                          storage: 3Gi

                mongos:
                  size: 1
        providerConfigRef:
          name: kubernetes-provider
    patches:
    - fromFieldPath: spec.name
      toFieldPath: spec.forProvider.manifest.metadata.name
    - fromFieldPath: spec.name
      toFieldPath: status.TemplateName
    readinessChecks:
    - type: None
