apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: dbclaim.psmdb.dbaas.percona.com
  labels:
    crossplane.io/xrd: xdbclaims.dbaas.percona.com
    engine: psmdb
    storage: default
    network: default

spec:

  writeConnectionSecretsToNamespace: crossplane-system

  compositeTypeRef:
    apiVersion: dbaas.percona.com/v1alpha1
    kind: XDBclaim

  resources:
  - name: CR
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: psmdb.percona.com/v1
            kind: PerconaServerMongoDB
            metadata:
              name: psmdb-default-template
              namespace: default
            spec:
              crVersion: 1.13.0
              image: percona/percona-server-mongodb:5.0.11-10
              allowUnsafeConfigurations: true
              upgradeOptions:
                apply: disabled
                schedule: "0 2 * * *"
              secrets:
                users: minimal-cluster
              replsets:
              - name: rs0
                size: 1
                volumeSpec:
                  persistentVolumeClaim:
                    resources:
                      requests:
                        storage: 3Gi
              sharding:
                enabled: true
                configsvrReplSet:
                  size: 1
                  volumeSpec:
                    persistentVolumeClaim:
                      resources:
                        requests:
                          storage: 3Gi
                mongos:
                  size: 1
        providerConfigRef:
          name: kubernetes-provider
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name
    - fromFieldPath: spec.clusterSize
      toFieldPath: spec.forProvider.manifest.spec.replsets[0].size
    readinessChecks:
    - type: None
